spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: book
  profiles:
    active: default
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  consumer:
    topic1:
      name: rental_rent
    topic2:
      name: rental_return
    topic3:
      name: overdue_clear
    groupid:
      name: member

server:
  port: 8082

logging:
  level:
    org.hibernate.SQL: debug
